name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3'
inputs:
  bucket:
    description: 'The name of the S3 bucket to deploy to'
    required: true
  bucket-region:
    description: 'The region of the S3 bucket to deploy to'
    required: false
    default: 'ap-northeast-1'
  dist-folder:
    description: 'The folder to deploy to the S3 bucket'
    required: true
outputs:
  website-url:
    description: 'The URL of the deployed website'
runs:
  using: 'node16'
  main: 'main.js'
 